# Use a Node.js image as the base for the frontend
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
# to leverage Docker's cache for npm install
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend application code
COPY . .

# Expose the port Vite development server runs on
EXPOSE 5173

# Command to start the Vite development server
CMD ["npm", "run", "dev"]