from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ProjectViewSet # Import your ProjectViewSet

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'projects', ProjectViewSet) # Register the ProjectViewSet at the 'projects' endpoint

app_name = 'portfolio_app' # Define app_name for namespacing URLs (still good practice)

urlpatterns = [
    # Include the API URLs generated by the router
    path('api/', include(router.urls)),
    # You can also add specific API paths if needed, e.g.:
    # path('api/my-custom-endpoint/', MyCustomAPIView.as_view(), name='custom-api'),
]
