# portfolio_project/portfolio_app/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ProjectViewSet, gemini_chat_view
from django.views.decorators.csrf import csrf_exempt # <--- NEW: Import csrf_exempt

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'projects', ProjectViewSet) # Register the ProjectViewSet at the 'projects' endpoint

app_name = 'portfolio_app' # Define app_name for namespacing URLs (still good practice)

urlpatterns = [
    # Include the API URLs generated by the router
    path('api/', include(router.urls)),
    # New API endpoint for the Gemini chatbot, now explicitly exempted from CSRF
    path('api/chat/', csrf_exempt(gemini_chat_view), name='gemini_chat'), # <--- MODIFIED THIS LINE
]
